name: npm publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install
      - run: git config --global user.name "Binyu Wang"
      - run: git config --global user.email "406279919@qq.com"
      - run: npm run build
      # - run: npm test
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      - run: npm publish --tag ${{ github.event.release.target_commitish }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: git push
        env:
          # The secret is passed automatically. Nothing to configure.
          github-token: ${{ secrets.GITHUB_TOKEN }}
